# Generated by Django 5.0.2 on 2024-03-28 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PisandoFuerte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adidas',
            options={'ordering': ['modelo']},
        ),
        migrations.AlterModelOptions(
            name='nike',
            options={'ordering': ['modelo']},
        ),
        migrations.AlterModelOptions(
            name='remeras',
            options={'ordering': ['color']},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
