# Generated by Django 5.0.2 on 2024-03-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PisandoFuerte', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
